logbook-servlet/src/main/java/org/zalando/logbook/servlet/LogbookFilter.java
logbook-servlet/src/main/java/org/zalando/logbook/servlet/TeeResponse.java

Fixed flush issue with buffering print writers

---

logbook-servlet/src/main/java/org/zalando/logbook/servlet/Attributes.java
logbook-servlet/src/main/java/org/zalando/logbook/servlet/TeeRequest.java
logbook-servlet/src/main/java/org/zalando/logbook/servlet/TeeResponse.java
logbook-servlet/src/test/java/org/zalando/logbook/servlet/MultiFilterSecurityTest.java
logbook-servlet/src/test/java/org/zalando/logbook/servlet/MultiFilterTest.java

Removed buffer-once semantic in multi-filter setups

---

README.md
logbook-core/src/main/java/org/zalando/logbook/DefaultHttpLogFormatter.java
logbook-core/src/main/java/org/zalando/logbook/JsonHttpLogFormatter.java
logbook-core/src/test/java/org/zalando/logbook/DefaultHttpLogFormatterTest.java
logbook-core/src/test/java/org/zalando/logbook/JsonHttpLogFormatterTest.java
logbook-httpclient/src/test/java/org/zalando/logbook/httpclient/LogbookHttpInterceptorsTest.java
logbook-servlet/src/test/java/org/zalando/logbook/servlet/WritingTest.java
logbook-spring-boot-starter/src/test/java/org/zalando/logbook/spring/HttpFormatterTest.java

Added classifier to JSON output

---

logbook-httpclient/src/main/java/org/zalando/logbook/httpclient/Request.java
logbook-httpclient/src/main/java/org/zalando/logbook/httpclient/Response.java
logbook-httpclient/src/test/java/org/zalando/logbook/httpclient/RequestTest.java

Fix logging of duplicate header names

---

logbook-spring-boot-starter/src/main/java/org/zalando/logbook/spring/LogbookAutoConfiguration.java
logbook-spring-boot-starter/src/main/java/org/zalando/logbook/spring/SecurityLogbookAutoConfiguration.java

Extracted security aspect of LogbookAutoConfiguration

---

README.md

Added correlation section to readme

---

README.md
logbook-core/src/main/java/org/zalando/logbook/BaseHttpMessage.java
logbook-core/src/main/java/org/zalando/logbook/BaseHttpResponse.java
logbook-core/src/main/java/org/zalando/logbook/DefaultLogbook.java
logbook-core/src/main/java/org/zalando/logbook/ForwardingRawHttpRequest.java
logbook-core/src/main/java/org/zalando/logbook/HttpMessage.java
logbook-core/src/main/java/org/zalando/logbook/Logbook.java
logbook-core/src/main/java/org/zalando/logbook/RawHttpResponse.java
logbook-core/src/test/java/org/zalando/logbook/DefaultHttpLogFormatterTest.java
logbook-core/src/test/java/org/zalando/logbook/DefaultLogbookTest.java
logbook-core/src/test/java/org/zalando/logbook/ForwardingRawHttpRequestTest.java
logbook-core/src/test/java/org/zalando/logbook/JsonHttpLogFormatterTest.java
logbook-core/src/test/java/org/zalando/logbook/MockHttpRequest.java
logbook-core/src/test/java/org/zalando/logbook/MockHttpResponse.java
logbook-core/src/test/java/org/zalando/logbook/MockRawHttpRequest.java
logbook-core/src/test/java/org/zalando/logbook/ObfuscatedHttpRequestTest.java
logbook-core/src/test/java/org/zalando/logbook/ObfuscatedHttpResponseTest.java
logbook-spring-boot-starter/src/test/java/org/zalando/logbook/spring/HttpFormatterTest.java
logbook-spring-boot-starter/src/test/java/org/zalando/logbook/spring/MockHttpRequest.java
logbook-spring-boot-starter/src/test/java/org/zalando/logbook/spring/MockRawHttpRequest.java

Conditional logging

---

logbook-core/src/main/java/org/zalando/logbook/RequestPredicates.java
logbook-core/src/test/java/org/zalando/logbook/RequestPredicatesTest.java

Changed semantics of requestTo(String)

---

README.md
logbook-api/src/main/java/org/zalando/logbook/BaseHttpMessage.java
logbook-api/src/main/java/org/zalando/logbook/BodyObfuscator.java
logbook-core/src/main/java/org/zalando/logbook/DefaultHttpLogFormatter.java
logbook-core/src/main/java/org/zalando/logbook/ForwardingHttpMessage.java
logbook-core/src/main/java/org/zalando/logbook/ForwardingRawHttpRequest.java
logbook-core/src/main/java/org/zalando/logbook/JsonHttpLogFormatter.java
logbook-core/src/test/java/org/zalando/logbook/DefaultHttpLogFormatterTest.java
logbook-core/src/test/java/org/zalando/logbook/ForwardingHttpRequestTest.java
logbook-core/src/test/java/org/zalando/logbook/ForwardingRawHttpRequestTest.java
logbook-core/src/test/java/org/zalando/logbook/JsonHttpLogFormatterTest.java
logbook-core/src/test/java/org/zalando/logbook/QueryParametersTest.java
logbook-httpclient/src/main/java/org/zalando/logbook/httpclient/LocalRequest.java
logbook-httpclient/src/main/java/org/zalando/logbook/httpclient/RemoteResponse.java
logbook-servlet/src/main/java/org/zalando/logbook/servlet/LocalResponse.java
logbook-servlet/src/main/java/org/zalando/logbook/servlet/NormalStrategy.java
logbook-servlet/src/main/java/org/zalando/logbook/servlet/RemoteRequest.java
logbook-servlet/src/main/java/org/zalando/logbook/servlet/SecurityStrategy.java
logbook-servlet/src/test/java/org/zalando/logbook/servlet/WritingTest.java
logbook-test/src/main/java/org/zalando/logbook/MockHttpRequest.java
logbook-test/src/main/java/org/zalando/logbook/MockHttpResponse.java
logbook-test/src/main/java/org/zalando/logbook/MockRawHttpRequest.java
logbook-test/src/main/java/org/zalando/logbook/MockRawHttpResponse.java

Added support for protocol version

---

logbook-api/src/main/java/org/zalando/logbook/BaseHttpMessage.java
logbook-api/src/test/java/org/zalando/logbook/BaseHttpMessageTest.java

Make headers immutable

---

README.md

Removed params from JSON example

---

logbook-spring-boot-starter/src/main/java/org/zalando/logbook/spring/LogbookAutoConfiguration.java

Added interceptors to AutoConfiguration

---

README.md

Added known issue to README

---

logbook-httpclient/src/main/java/org/zalando/logbook/httpclient/LocalRequest.java
logbook-httpclient/src/main/java/org/zalando/logbook/httpclient/RemoteResponse.java
logbook-servlet/src/main/java/org/zalando/logbook/servlet/LocalResponse.java
logbook-servlet/src/main/java/org/zalando/logbook/servlet/RemoteRequest.java

Switched to UTF-8

---

logbook-servlet/src/main/java/org/zalando/logbook/servlet/LogbookFilter.java
logbook-servlet/src/main/java/org/zalando/logbook/servlet/NormalStrategy.java
logbook-servlet/src/main/java/org/zalando/logbook/servlet/UnauthorizedHttpRequest.java
logbook-servlet/src/main/java/org/zalando/logbook/servlet/UnauthorizedRawHttpRequest.java
logbook-servlet/src/test/java/org/zalando/logbook/servlet/ErrorDispatchTest.java
logbook-servlet/src/test/java/org/zalando/logbook/servlet/UnauthorizedHttpRequestTest.java

Requests in error dispatch are now logged without a body

---

logbook-spring-boot-starter/src/main/java/org/zalando/logbook/spring/LogbookAutoConfiguration.java
logbook-spring-boot-starter/src/main/java/org/zalando/logbook/spring/LogbookHttpClientAutoConfiguration.java
logbook-spring-boot-starter/src/main/java/org/zalando/logbook/spring/LogbookSecurityAutoConfiguration.java
logbook-spring-boot-starter/src/main/resources/META-INF/spring.factories
logbook-spring-boot-starter/src/test/java/org/zalando/logbook/spring/Application.java

Added support to exclude http client

---

README.md
logbook-core/src/main/java/org/zalando/logbook/ChunkingHttpLogWriter.java
logbook-core/src/test/java/org/zalando/logbook/ChunkingHttpLogWriterTest.java
logbook-spring-boot-starter/src/main/java/org/zalando/logbook/spring/LogbookAutoConfiguration.java
logbook-spring-boot-starter/src/main/java/org/zalando/logbook/spring/LogbookProperties.java
logbook-spring-boot-starter/src/test/java/org/zalando/logbook/spring/WriteChunkingTest.java

Added chunking support

---

logbook-core/src/main/java/org/zalando/logbook/HeaderFilters.java
logbook-core/src/test/java/org/zalando/logbook/HeaderFiltersTest.java

Fixes #151 
I have added a couple of factory methods into `HeaderFilters` to allow removal of headers, though I am not sure that it is a good idea to remove headers in general.

GH-151 Allows removal of headers

---

logbook-servlet/src/main/java/org/zalando/logbook/servlet/LocalResponse.java
logbook-servlet/src/test/java/org/zalando/logbook/servlet/LocalResponseTest.java

GH-146 Delegates getOutputStream and getWriter after withoutBody was called

---

logbook-api/src/main/java/org/zalando/logbook/BaseHttpMessage.java
logbook-api/src/main/java/org/zalando/logbook/BodyFilter.java
logbook-core/src/main/java/org/zalando/logbook/BodyFilters.java
logbook-core/src/main/java/org/zalando/logbook/JsonHttpLogFormatter.java
logbook-core/src/test/java/org/zalando/logbook/JsonHttpLogFormatterTest.java
logbook-servlet/src/main/java/org/zalando/logbook/servlet/LocalResponse.java
logbook-servlet/src/main/java/org/zalando/logbook/servlet/RemoteRequest.java
logbook-servlet/src/test/java/org/zalando/logbook/servlet/LocalResponseTest.java

Fixed missing content-type

---

README.md
logbook-core/src/main/java/org/zalando/logbook/CurlHttpLogFormatter.java
logbook-core/src/test/java/org/zalando/logbook/CurlHttpLogFormatterTest.java
logbook-spring-boot-starter/src/main/java/org/zalando/logbook/spring/LogbookAutoConfiguration.java
logbook-spring-boot-starter/src/test/java/org/zalando/logbook/spring/FormatStyleCurlTest.java

Added curl request formatter

---

README.md
logbook-api/src/main/java/org/zalando/logbook/Correlation.java
logbook-api/src/main/java/org/zalando/logbook/package-info.java
logbook-core/src/main/java/org/zalando/logbook/ChunkingHttpLogWriter.java
logbook-core/src/main/java/org/zalando/logbook/DefaultHttpLogFormatter.java
logbook-core/src/main/java/org/zalando/logbook/DefaultLogbook.java
logbook-core/src/main/java/org/zalando/logbook/JsonHttpLogFormatter.java
logbook-core/src/test/java/org/zalando/logbook/ChunkingHttpLogWriterTest.java
logbook-core/src/test/java/org/zalando/logbook/CurlHttpLogFormatterTest.java
logbook-core/src/test/java/org/zalando/logbook/DefaultHttpLogFormatterTest.java
logbook-core/src/test/java/org/zalando/logbook/DefaultHttpLogWriterLevelTest.java
logbook-core/src/test/java/org/zalando/logbook/DefaultHttpLogWriterTest.java
logbook-core/src/test/java/org/zalando/logbook/JsonHttpLogFormatterTest.java
logbook-core/src/test/java/org/zalando/logbook/StreamHttpLogWriterTest.java
logbook-httpclient/src/main/java/org/zalando/logbook/httpclient/package-info.java
logbook-spring-boot-starter/src/main/java/org/zalando/logbook/spring/package-info.java
logbook-test/src/main/java/org/zalando/logbook/package-info.java

Added logging of durations

---

.travis.yml
logbook-servlet/pom.xml
logbook-spring-boot-starter/pom.xml
logbook-spring-boot-starter/src/main/java/org/zalando/logbook/spring/LogbookAutoConfiguration.java
logbook-spring-boot-starter/src/test/resources/application.yml
logbook-spring-boot-starter/src/test/resources/exclude.yml
logbook-spring-boot-starter/src/test/resources/headers.yml
logbook-spring-boot-starter/src/test/resources/parameters.yml
pom.xml

Added Spring Boot 2.0 build profile

---

logbook-core/src/main/java/org/zalando/logbook/Conditions.java
logbook-core/src/test/java/org/zalando/logbook/ConditionsTest.java

Supersedes https://github.com/zalando/logbook/pull/179
@innokenty Hi. I have somehow missed your point within #179 
I have created this PR to deal with NPE issue. Thanks for pushing this issue!

GH-179 Fixes NPE in header(String, Predicate)

---

logbook-core/src/main/java/org/zalando/logbook/Conditions.java
logbook-core/src/test/java/org/zalando/logbook/ConditionsTest.java
logbook-core/src/test/java/org/zalando/logbook/MediaTypeQueryTest.java

Added support to query for absent content type

---

logbook-servlet/src/main/java/org/zalando/logbook/servlet/NormalStrategy.java

Fixes #143
@iribaar @wyzssw @cybuch

Moved flushing of async response to correct branch

---

logbook-spring-boot-starter/pom.xml
pom.xml

JUnit5 is released. 
so, update junit5 dependencies from RC version.

Update JUnit5 dependencies

---

logbook-core/src/main/java/org/zalando/logbook/BodyReplacers.java

Added support for more streaming media types

---

pom.xml

This PR fixes followings.
* upgrade to released version in Spring 5
* upgrade to new milestone version in Spring Boot 2

Update spring dependencies

---

pom.xml

This PR fixes followings.
* upgrade to released version in Spring 4
* upgrade version of Spring Security
* upgrade to new milestone version in Spring Boot 2

Update spring version

---

logbook-core/src/main/java/org/zalando/logbook/DefaultLogbook.java

GH-198 Uses pseudo-random generator to create correlation ids

---

README.md
logbook-httpclient/src/test/java/org/zalando/logbook/httpclient/AbstractHttpTest.java
logbook-httpclient/src/test/java/org/zalando/logbook/httpclient/LogbookHttpAsyncResponseConsumerTest.java
logbook-httpclient/src/test/java/org/zalando/logbook/httpclient/LogbookHttpInterceptorsTest.java
logbook-okhttp/pom.xml
logbook-okhttp/src/main/java/org/zalando/logbook/okhttp/LocalRequest.java
logbook-okhttp/src/main/java/org/zalando/logbook/okhttp/LogbookInterceptor.java
logbook-okhttp/src/main/java/org/zalando/logbook/okhttp/RemoteResponse.java
logbook-okhttp/src/test/java/org/zalando/logbook/okhttp/LocalRequestTest.java
logbook-okhttp/src/test/java/org/zalando/logbook/okhttp/LogbookInterceptorTest.java
pom.xml

Added support for OkHttp

---

pom.xml

Upgrade spring boot release version.

Bump spring boot version

---

logbook-api/src/main/java/org/zalando/logbook/Precorrelation.java
logbook-core/src/main/java/org/zalando/logbook/ChunkingHttpLogWriter.java
logbook-core/src/main/java/org/zalando/logbook/DefaultHttpLogWriter.java
logbook-core/src/main/java/org/zalando/logbook/DefaultLogbook.java
logbook-core/src/main/java/org/zalando/logbook/JsonHttpLogFormatter.java
logbook-core/src/main/java/org/zalando/logbook/Origins.java
logbook-core/src/test/java/org/zalando/logbook/ChunkingHttpLogWriterTest.java
logbook-core/src/test/java/org/zalando/logbook/CurlHttpLogFormatterTest.java
logbook-core/src/test/java/org/zalando/logbook/DefaultHttpLogFormatterTest.java
logbook-core/src/test/java/org/zalando/logbook/DefaultHttpLogWriterLevelTest.java
logbook-core/src/test/java/org/zalando/logbook/DefaultHttpLogWriterTest.java
logbook-core/src/test/java/org/zalando/logbook/DelayedResponseLogWriter.java
logbook-core/src/test/java/org/zalando/logbook/EnforceCoverageTest.java
logbook-core/src/test/java/org/zalando/logbook/JsonHttpLogFormatterTest.java
logbook-core/src/test/java/org/zalando/logbook/SeparateRequestResponseLogWriter.java
logbook-core/src/test/java/org/zalando/logbook/StreamHttpLogWriterTest.java

Added original request to Precorrelation

---

logbook-core/src/main/java/org/zalando/logbook/DefaultLogbook.java

Replaced Random with ThreadLocalRandom

---

logbook-api/src/main/java/org/zalando/logbook/Correlation.java
logbook-api/src/main/java/org/zalando/logbook/Precorrelation.java
logbook-api/src/main/java/org/zalando/logbook/RawHttpRequest.java
logbook-api/src/main/java/org/zalando/logbook/RawHttpResponse.java
logbook-core/src/main/java/org/zalando/logbook/PatternLike.java
logbook-core/src/test/java/org/zalando/logbook/GlobTest.java
logbook-core/src/test/java/org/zalando/logbook/HeaderFiltersTest.java
logbook-httpclient/src/test/java/org/zalando/logbook/httpclient/LogbookHttpAsyncResponseConsumerTest.java
logbook-httpclient/src/test/java/org/zalando/logbook/httpclient/LogbookHttpInterceptorsTest.java
logbook-httpclient/src/test/java/org/zalando/logbook/httpclient/RemoteResponseTest.java
logbook-okhttp/src/test/java/org/zalando/logbook/okhttp/LogbookInterceptorTest.java
logbook-servlet/src/main/java/org/zalando/logbook/servlet/HttpFilter.java
logbook-servlet/src/test/java/org/zalando/logbook/servlet/EnforceCoverageTest.java
logbook-servlet/src/test/java/org/zalando/logbook/servlet/ExampleController.java
logbook-spring-boot-starter/src/main/java/org/zalando/logbook/spring/LogbookAutoConfiguration.java
logbook-spring-boot-starter/src/test/java/org/zalando/logbook/spring/FormatStyleCustomTest.java

https://app.codacy.com/app/whiskeysierra/logbook/issues
Get # of issues in codacy down to 0.

Fixed some issues

---

.travis.yml
README.md
logbook-spring-boot-starter/pom.xml
pom.xml

Updated README and renamed spring5 profiles

---

README.md
logbook-api/src/test/java/org/zalando/logbook/EnforceCoverageTest.java
logbook-api/src/test/java/org/zalando/logbook/Mockbook.java
logbook-core/src/main/java/org/zalando/logbook/BodyFilters.java
logbook-core/src/test/java/org/zalando/logbook/BodyFiltersTest.java
logbook-servlet/src/test/java/org/zalando/logbook/servlet/LogbookFilterTest.java
logbook-spring-boot-starter/src/main/java/org/zalando/logbook/spring/LogbookAutoConfiguration.java
logbook-spring-boot-starter/src/main/java/org/zalando/logbook/spring/LogbookProperties.java
logbook-spring-boot-starter/src/test/java/org/zalando/logbook/spring/WriteBodyMaxSizeTest.java

Renamed configuration key, refactored and reformatted some parts

---

README.md
logbook-bom/pom.xml
logbook-jaxrs/pom.xml
logbook-jaxrs/src/main/java/org/zalando/logbook/jaxrs/Accessor.java
logbook-jaxrs/src/main/java/org/zalando/logbook/jaxrs/ClientLoggingFilter.java
logbook-jaxrs/src/main/java/org/zalando/logbook/jaxrs/LocalRequest.java
logbook-jaxrs/src/main/java/org/zalando/logbook/jaxrs/LocalResponse.java
logbook-jaxrs/src/main/java/org/zalando/logbook/jaxrs/RemoteRequest.java
logbook-jaxrs/src/main/java/org/zalando/logbook/jaxrs/RemoteResponse.java
logbook-jaxrs/src/main/java/org/zalando/logbook/jaxrs/RequestResponseLogProcessingException.java
logbook-jaxrs/src/main/java/org/zalando/logbook/jaxrs/ServerLoggingFilter.java
logbook-jaxrs/src/main/java/org/zalando/logbook/jaxrs/TeeOutputStream.java
logbook-jaxrs/src/main/java/org/zalando/logbook/jaxrs/Utils.java
logbook-jaxrs/src/test/java/org/zalando/logbook/jaxrs/ClientLoggingFilterTest.java
logbook-jaxrs/src/test/java/org/zalando/logbook/jaxrs/JerseyClientAndServerTest.java
logbook-jaxrs/src/test/java/org/zalando/logbook/jaxrs/ServerLoggingFilterTest.java
logbook-jaxrs/src/test/java/org/zalando/logbook/jaxrs/UnitTestSetupException.java
logbook-jaxrs/src/test/java/org/zalando/logbook/jaxrs/UtilsTest.java
logbook-jaxrs/src/test/java/org/zalando/logbook/jaxrs/testing/support/TestModel.java
logbook-jaxrs/src/test/java/org/zalando/logbook/jaxrs/testing/support/TestWebService.java
pom.xml

Support for using Logbook with JAX-RS clients and servers via filters
Support for a Java standard API (JAX-RS)

add JAX-RS support (on client and server) for logbook

---

.travis.yml
logbook-spring-boot-starter/pom.xml
pom.xml

Made Spring 5 the default

---

logbook-spring-boot-starter/pom.xml
logbook-spring-boot-starter/src/main/resources/META-INF/additional-spring-configuration-metadata.json

Configured spring boot's annotation processor to generate metadata about properties.
Improve IDE support

Added spring configuration metadata file

---

README.md

Just suggesting some edits to the readme to help the next person who comes along. 
fixes #316

Configure logger to trace

---

README.md
logbook-spring-boot-starter/src/main/java/org/zalando/logbook/spring/LogbookAutoConfiguration.java
logbook-spring-boot-starter/src/main/java/org/zalando/logbook/spring/LogbookProperties.java
logbook-spring-boot-starter/src/test/java/org/zalando/logbook/spring/IncludeTest.java
logbook-spring-boot-starter/src/test/resources/application-include.yml

Provide `include` configuration option
unlikely to already existed `exclude` option, sometimes is much more convenient to specify allowed only patterns

add include configuration options

---

pom.xml

Bumped spring versions

---

logbook-servlet/pom.xml

Add javax activation as a dependency to logbook-servlet

---

logbook-api/src/main/java/org/zalando/logbook/BodyReplacer.java
logbook-api/src/test/java/org/zalando/logbook/BodyReplacerTest.java
logbook-core/src/main/java/org/zalando/logbook/BodyReplacers.java

Switched from compound to composite

---

cve-suppressions.xml

Suppressed false positive CVE-2018-1258

---

logbook-servlet/src/main/java/org/zalando/logbook/servlet/LogbookFilter.java
pom.xml

Fixed CVE-2019-3795

---

logbook-servlet/src/test/java/org/zalando/logbook/servlet/MultiFilterSecurityTest.java
logbook-spring-boot-starter/pom.xml

Improved tests

---

logbook-logstash/src/main/java/org/zalando/logbook/logstash/AutodetectPrettyPrintingMarker.java
logbook-logstash/src/main/java/org/zalando/logbook/logstash/DefaultPrettyPrinterDecorator.java
logbook-logstash/src/main/java/org/zalando/logbook/logstash/LogstashLogbackSink.java
logbook-logstash/src/test/java/org/zalando/logbook/logstash/LogbackLogstashSinkTest.java
logbook-logstash/src/test/java/org/zalando/logbook/logstash/PrettyPrintingStaticAppender.java
logbook-logstash/src/test/java/org/zalando/logbook/logstash/StaticAppender.java

Minor code style issues

---

logbook-bom/pom.xml

Added logstash to bom

---

.travis.yml

See https://github.com/zalando/logbook/issues/514

Move travis-ci to openjdk8

---

.gitignore
logbook-jmh/README.md
logbook-jmh/pom.xml
logbook-jmh/src/main/java/org/zalando/logbook/HeaderBenchmark.java
logbook-jmh/src/main/java/org/zalando/logbook/HeaderState.java
logbook-jmh/src/main/java/org/zalando/logbook/HttpLogFormatterBenchmark.java
logbook-jmh/src/main/java/org/zalando/logbook/HttpLogFormatterState.java
logbook-jmh/src/main/java/org/zalando/logbook/LogbookBenchmark.java
logbook-jmh/src/main/java/org/zalando/logbook/LogbookState.java
logbook-jmh/src/main/java/org/zalando/logbook/NoopHttpLogFormatter.java
logbook-jmh/src/main/java/org/zalando/logbook/RequestResponseState.java
logbook-jmh/src/main/java/org/zalando/logbook/jmh/DefaultCorrelation.java
logbook-jmh/src/main/java/org/zalando/logbook/jmh/DefaultPrecorrelation.java
logbook-jmh/src/main/java/org/zalando/logbook/jmh/NOPAppender.java
logbook-jmh/src/main/resources/logback.xml
logbook-jmh/src/test/java/org/zalando/logbook/jmh/TestDefaultCorrelation.java
pom.xml

Basic JHM module for performance testing
New module with a few baseline tests and documentation.
We're using this library for logging in our microservices and would like to keep the resource usage and response time low.
I added a seperate README for the module. Perhaps this checklist should be updated with an item for how a PR affects the performance.

JMH module

---

README.md

formatting correcting dependency of the logbook-json
formatting correcting dependency of the logbook-json
The formatting was incorrect in readme.md, the solution improves the reading of the doc.

Formatting correcting dependency of the logbook-json in Readme.md

---

README.md

Fixed incorrect group id in README

---

logbook-jmh/src/test/java/org/zalando/logbook/jmh/TestDefaultCorrelation.java
logbook-json/src/main/java/org/zalando/logbook/json/CompactingJsonBodyFilter.java
logbook-json/src/main/java/org/zalando/logbook/json/FastCompactingJsonBodyFilter.java
logbook-json/src/main/java/org/zalando/logbook/json/JsonCompactor.java
logbook-json/src/main/java/org/zalando/logbook/json/ParsingJsonCompactor.java
logbook-json/src/main/java/org/zalando/logbook/json/PrettyPrintingJsonBodyFilter.java
logbook-json/src/main/java/org/zalando/logbook/json/StringReplaceJsonCompactor.java
logbook-json/src/test/java/org/zalando/logbook/json/FastCompactingJsonBodyFilterTest.java

Added fast compactor alternative

---

logbook-json/src/main/java/org/zalando/logbook/json/JsonBodyFilters.java
logbook-json/src/test/java/org/zalando/logbook/json/JsonBodyFiltersTest.java

Added primitive json number replacement filter

---

logbook-spring-boot-autoconfigure/src/main/resources/META-INF/additional-spring-configuration-metadata.json

Added spring metadata for logbook.strategy

---

cve-suppressions.xml
pom.xml

https://github.com/jeremylong/DependencyCheck/issues/1991

Properly suppressed Spring Security vulnerability

---

README.md
logbook-api/src/main/java/org/zalando/logbook/Correlation.java
logbook-api/src/main/java/org/zalando/logbook/Precorrelation.java
logbook-core/src/main/java/org/zalando/logbook/CommonsLogFormatSink.java
logbook-core/src/main/java/org/zalando/logbook/CurlHttpLogFormatter.java
logbook-core/src/main/java/org/zalando/logbook/DefaultLogbook.java
logbook-core/src/main/java/org/zalando/logbook/PathFilters.java
logbook-core/src/test/java/org/zalando/logbook/BodyFiltersTest.java
logbook-core/src/test/java/org/zalando/logbook/ChunkingSinkTest.java
logbook-core/src/test/java/org/zalando/logbook/CommonsLogFormatSinkTest.java
logbook-core/src/test/java/org/zalando/logbook/CurlHttpLogFormatterTest.java
logbook-core/src/test/java/org/zalando/logbook/DefaultHttpLogFormatterTest.java
logbook-core/src/test/java/org/zalando/logbook/DefaultHttpLogWriterTest.java
logbook-core/src/test/java/org/zalando/logbook/DefaultPathFilterTest.java
logbook-core/src/test/java/org/zalando/logbook/SimplePrecorrelationTest.java
logbook-core/src/test/java/org/zalando/logbook/SplunkHttpLogFormatterTest.java
logbook-core/src/test/java/org/zalando/logbook/StreamHttpLogWriterTest.java
logbook-jmh/src/main/java/org/zalando/logbook/RequestResponseState.java
logbook-jmh/src/main/java/org/zalando/logbook/jmh/DefaultCorrelation.java
logbook-jmh/src/main/java/org/zalando/logbook/jmh/DefaultPrecorrelation.java
logbook-json/src/test/java/org/zalando/logbook/json/JsonHttpLogFormatterTest.java

Added support for Common Log Format

---

pom.xml

Removed direct dependency to junit-platform

---

logbook-httpclient/src/main/java/org/zalando/logbook/httpclient/LocalRequest.java
logbook-httpclient/src/test/java/org/zalando/logbook/httpclient/LogbookHttpInterceptorsPutTest.java

GH-585 Fixed PUT without body

---

logbook-jmh/src/main/java/org/zalando/logbook/HttpLogFormatterBenchmark.java
logbook-jmh/src/main/java/org/zalando/logbook/HttpLogFormatterState.java
logbook-json/src/main/java/org/zalando/logbook/json/FastJsonHttpLogFormatter.java
logbook-json/src/test/java/org/zalando/logbook/json/JsonHttpLogFormatterTest.java

Added fast json formatter

---

logbook-json/src/main/java/org/zalando/logbook/json/CompactingJsonBodyFilter.java
logbook-json/src/main/java/org/zalando/logbook/json/JacksonJsonFieldBodyFilter.java
logbook-json/src/main/java/org/zalando/logbook/json/ParsingJsonCompactor.java
logbook-json/src/main/java/org/zalando/logbook/json/PrettyPrintingJsonBodyFilter.java
logbook-json/src/test/java/org/zalando/logbook/json/PrettyPrintingJsonBodyFilterTest.java

A bit more low-level JSON processing.
Work in progress; for discussion while waiting for https://github.com/zalando/logbook/pull/580. Will require adjustment.
Stream JSON events wherever possible. Pass marginally more low-level types.
Avoid reading JSON trees into memory.

Streaming / more low-level JSON processing

---

logbook-json/src/main/java/org/zalando/logbook/json/JsonBodyFilters.java
logbook-json/src/test/java/org/zalando/logbook/json/JsonBodyFiltersTest.java

Unrelated null properties are left unchanged

---

logbook-json/src/main/java/org/zalando/logbook/json/JsonBodyFilters.java
logbook-json/src/test/java/org/zalando/logbook/json/JsonBodyFiltersTest.java

Added property predicate to JSON filters

---

logbook-core/src/main/java/org/zalando/logbook/BodyFilters.java
logbook-core/src/main/java/org/zalando/logbook/DefaultPathFilter.java
logbook-core/src/main/java/org/zalando/logbook/QueryFilters.java
logbook-core/src/test/java/org/zalando/logbook/QueryFiltersTest.java
logbook-spring-boot-autoconfigure/src/main/java/org/zalando/logbook/autoconfigure/LogbookAutoConfiguration.java

Added query replace predicate support

---

README.md
logbook-api/src/main/java/org/zalando/logbook/CorrelationId.java
logbook-api/src/main/java/org/zalando/logbook/LogbookCreator.java
logbook-api/src/main/java/org/zalando/logbook/LogbookFactory.java
logbook-api/src/test/java/org/zalando/logbook/Mockbook.java
logbook-api/src/test/java/org/zalando/logbook/MockbookFactory.java
logbook-core/src/main/java/org/zalando/logbook/DefaultCorrelationId.java
logbook-core/src/main/java/org/zalando/logbook/DefaultLogbook.java
logbook-core/src/main/java/org/zalando/logbook/DefaultLogbookFactory.java
logbook-core/src/test/java/org/zalando/logbook/ChunkingSinkTest.java
logbook-core/src/test/java/org/zalando/logbook/DefaultHttpLogWriterTest.java
logbook-core/src/test/java/org/zalando/logbook/SimplePrecorrelationTest.java
logbook-core/src/test/java/org/zalando/logbook/StreamHttpLogWriterTest.java
logbook-jmh/src/main/java/org/zalando/logbook/LogbookState.java
logbook-spring-boot-autoconfigure/src/main/java/org/zalando/logbook/autoconfigure/LogbookAutoConfiguration.java

Made correlation id customizable

---

README.md
logbook-core/src/main/java/org/zalando/logbook/DefaultPathFilter.java
logbook-core/src/main/java/org/zalando/logbook/PathFilters.java

Fixed wrong default configuration in README

---

README.md

Added logback-access to alternatives

---

logbook-servlet/src/test/java/org/zalando/logbook/servlet/AsyncDispatchTest.java
pom.xml

Fixed flaky test

---

.github/workflows/build.yaml

Disabled coverage step for forks

---

logbook-json/src/main/java/org/zalando/logbook/json/JsonHttpLogFormatter.java

Fixed old code example in javadoc

---

README.md
logbook-servlet/src/main/java/org/zalando/logbook/servlet/FormRequestMode.java
logbook-servlet/src/main/java/org/zalando/logbook/servlet/LogbookFilter.java
logbook-servlet/src/main/java/org/zalando/logbook/servlet/RemoteRequest.java
logbook-servlet/src/test/java/org/zalando/logbook/servlet/FormRequestModeTest.java
logbook-servlet/src/test/java/org/zalando/logbook/servlet/FormRequestTest.java
logbook-spring-boot-autoconfigure/src/main/java/org/zalando/logbook/autoconfigure/LogbookAutoConfiguration.java
logbook-spring-boot-autoconfigure/src/main/java/org/zalando/logbook/autoconfigure/LogbookProperties.java

Fixes #701
Made form request mode configurable using configuration properties.

Made form request mode configurable via configuration properties

---

logbook-core/src/main/java/org/zalando/logbook/CookieHeaderFilter.java
logbook-core/src/main/java/org/zalando/logbook/HeaderFilters.java
logbook-core/src/test/java/org/zalando/logbook/CookieHeaderFilterTest.java

Added Cookie/Set-Cookie header filter

---

logbook-api/src/main/java/org/zalando/logbook/BodyFilter.java
logbook-api/src/main/java/org/zalando/logbook/NonMergeableBodyFilterPair.java
logbook-api/src/main/java/org/zalando/logbook/NoneBodyFilter.java
logbook-api/src/test/java/org/zalando/logbook/BodyFilterMergeTest.java
logbook-json/src/main/java/org/zalando/logbook/json/AccessTokenBodyFilter.java
logbook-json/src/main/java/org/zalando/logbook/json/CompactingJsonBodyFilter.java
logbook-json/src/main/java/org/zalando/logbook/json/JacksonJsonFieldBodyFilter.java
logbook-json/src/main/java/org/zalando/logbook/json/JsonBodyFilters.java
logbook-json/src/main/java/org/zalando/logbook/json/PrimitiveJsonPropertyBodyFilter.java
logbook-json/src/main/resources/META-INF/services/org.zalando.logbook.BodyFilter
logbook-json/src/test/java/org/zalando/logbook/json/DefaultBodyFilterTest.java
logbook-json/src/test/java/org/zalando/logbook/json/JsonBodyFilterMergeTest.java
logbook-json/src/test/java/org/zalando/logbook/json/JsonBodyFiltersTest.java
logbook-spring-boot-autoconfigure/src/main/java/org/zalando/logbook/autoconfigure/LogbookAutoConfiguration.java

Added ability to merge/optimize body filters 

---

logbook-netty/src/main/java/org/zalando/logbook/netty/HeaderSupport.java
logbook-netty/src/main/java/org/zalando/logbook/netty/Request.java
logbook-netty/src/main/java/org/zalando/logbook/netty/Response.java
logbook-netty/src/test/java/org/zalando/logbook/netty/LogbookClientHandlerTest.java

Fixes broken master because netty branch was not up to date.

Fixed HttpHeaders support

---

logbook-json/src/main/java/org/zalando/logbook/json/JsonBodyFilters.java
logbook-json/src/main/java/org/zalando/logbook/json/PrimitiveJsonPropertyBodyFilter.java
logbook-json/src/test/java/org/zalando/logbook/json/JsonBodyFiltersTest.java

Nested properties are now filtered correctly

---

logbook-bom/pom.xml

Fixed incorrect logbook-netty version in bom

---

README.md
logbook-core/src/main/java/org/zalando/logbook/BodyFilters.java
logbook-core/src/test/java/org/zalando/logbook/BodyFiltersTest.java

Enabled oauth request filter (form) by default

---

README.md

Updated docs to promote support for Micronaut

---

logbook-spring-boot-autoconfigure/src/test/java/org/zalando/logbook/autoconfigure/ExcludeTest.java

Refactored ExcludeTest to correctly use new setup

---

logbook-spring-boot-autoconfigure/src/main/java/org/zalando/logbook/autoconfigure/LogbookProperties.java

Remove final from formRequestMode property. Fixes #797

---

cve-suppressions.xml

We're not running Kotlin per-se, that's the resonsibility of our users
Fix broken master build.

Suppressed CVE-2020-15824

---

logbook-core/src/main/java/org/zalando/logbook/DefaultPathFilter.java

Extract common part of if condition. 
Extract common part of if condition. 
Extract common part of if condition. Is is code style fix.

Extract common part of if

---

logbook-core/src/main/java/org/zalando/logbook/ChunkingSink.java
logbook-core/src/test/java/org/zalando/logbook/ChunkingSinkTest.java

Fixes chunking of empty bodies.

---

cve-suppressions.xml
pom.xml

Suppressed CVE-2020-5421

---

logbook-bom/pom.xml
logbook-spring-boot-autoconfigure/src/main/java/org/zalando/logbook/autoconfigure/LogbookAutoConfiguration.java
logbook-spring-boot-webflux-autoconfigure/pom.xml
logbook-spring-boot-webflux-autoconfigure/src/main/java/org/zalando/logbook/autoconfigure/webflux/LogbookWebFluxAutoConfiguration.java
logbook-spring-boot-webflux-autoconfigure/src/main/resources/META-INF/spring.factories
logbook-spring-boot-webflux-autoconfigure/src/test/java/org/zalando/logbook/autoconfigure/webflux/LogbookWebfluxTest.java
logbook-spring-boot-webflux-autoconfigure/src/test/java/org/zalando/logbook/autoconfigure/webflux/NettyClientCustomizerTest.java
logbook-spring-boot-webflux-autoconfigure/src/test/java/org/zalando/logbook/autoconfigure/webflux/NettyServerCustomizerDisabledTest.java
logbook-spring-boot-webflux-autoconfigure/src/test/java/org/zalando/logbook/autoconfigure/webflux/NettyServerCustomizerTest.java
pom.xml

Related to https://github.com/zalando/logbook/issues/740

Spring webflux autoconfiguration

---

pom.xml

Fixed incorrect spring version setup.

Fixed spring versions

---

README.md

Fixes #923

---

logbook-core/src/main/java/org/zalando/logbook/CookieHeaderFilter.java
logbook-core/src/main/java/org/zalando/logbook/HeaderFilters.java
logbook-core/src/test/java/org/zalando/logbook/CookieHeaderFilterTest.java

Instead of replacing with a constant string, cookie values could be configured for masking with a `Function`
Resolves #964
I can add a tiny doc for this if requested.

Add cookie value replacer function

---

logbook-api/pom.xml
logbook-bom/pom.xml
logbook-common/pom.xml
logbook-core/pom.xml
logbook-httpclient/pom.xml
logbook-jaxrs/pom.xml
logbook-jmh/pom.xml
logbook-json/pom.xml
logbook-logstash/pom.xml
logbook-netty/pom.xml
logbook-okhttp/pom.xml
logbook-okhttp2/pom.xml
logbook-servlet/pom.xml
logbook-spring-boot-autoconfigure/pom.xml
logbook-spring-boot-starter/pom.xml
logbook-spring-boot-webflux-autoconfigure/pom.xml
logbook-spring/pom.xml
logbook-test/pom.xml
pom.xml

Release 2.5.0

---

release.sh

Fixed release script

---

logbook-netty/pom.xml
logbook-spring-boot-webflux-autoconfigure/pom.xml

Bumped netty

---

logbook-core/src/test/java/org/zalando/logbook/CommonsLogFormatSinkTest.java
logbook-netty/src/main/java/org/zalando/logbook/netty/Request.java
logbook-netty/src/main/java/org/zalando/logbook/netty/Response.java
logbook-netty/src/test/java/org/zalando/logbook/netty/RequestUnitTest.java

According to Norman Maurer (netty maintainer), this is the only way to extract scheme:
https://stackoverflow.com/questions/36280376/get-base-uri-of-io-netty-handler-codec-http-httprequest#comment109701966_36281043

Logbook-netty more extractions

---

logbook-core/src/main/java/org/zalando/logbook/Conditions.java
logbook-core/src/test/java/org/zalando/logbook/ConditionsTest.java

Applied code style

---

pom.xml

Move test scope of guava from dependencyManagement to dependencies
Move test scope of guava from dependencyManagement to dependencies
See #1084

#1084 Guava test scope

---

logbook-netty/src/main/java/org/zalando/logbook/netty/LogbookServerHandler.java

Possible fix for #1071

---

CHANGELOG.md
release.sh

Added first changelog draft

---

logbook-spring-boot-autoconfigure/src/main/resources/META-INF/additional-spring-configuration-metadata.json

Add `logbook.secure-filter.enabled` to the additional-spring-configuration-metadata.json

---

logbook-ktor-client/src/main/kotlin/org/zalando/logbook/client/LogbookClient.kt
logbook-ktor-common/src/main/kotlin/org/zalando/logbook/common/State.kt
logbook-ktor-server/src/main/kotlin/org/zalando/logbook/server/LogbookServer.kt

logbook-ktor test and double-read fixes

---

logbook-core/src/main/java/org/zalando/logbook/DynamicPathFilter.java
logbook-core/src/main/java/org/zalando/logbook/PathFilters.java
logbook-core/src/test/java/org/zalando/logbook/DynamicPathFilterTest.java
logbook-core/src/test/java/org/zalando/logbook/FilteredHttpRequestTest.java

Added a new method to PathFilters with a String UnaryOperator to allow the dynamic customization of replacing target value.
Resolves #1164

Dynamic path parameters replacing of PathFilters

---

logbook-api/src/main/java/org/zalando/logbook/ContentType.java
logbook-api/src/main/java/org/zalando/logbook/Fold.java
logbook-api/src/main/java/org/zalando/logbook/HttpHeaders.java
logbook-api/src/main/java/org/zalando/logbook/HttpMessage.java
logbook-api/src/main/java/org/zalando/logbook/RequestURI.java
logbook-api/src/test/java/org/zalando/logbook/ContentTypeTest.java
logbook-api/src/test/java/org/zalando/logbook/HttpHeadersTest.java
logbook-api/src/test/java/org/zalando/logbook/HttpMessageTest.java
logbook-spring-webflux/src/main/java/org/zalando/logbook/spring/webflux/ClientResponse.java

Provide default implementation for some HttpMessage methods.

Make some HttpMessage methods default

---

logbook-json/src/main/java/org/zalando/logbook/json/JsonPathBodyFilters.java
logbook-json/src/test/java/org/zalando/logbook/json/JsonPathBodyFiltersTest.java
logbook-json/src/test/resources/cars-unwrapped-array.json

Fix PathNotFoundException when body is unwrapped Array

Fix PathNotFoundException when body is unwrapped Array

---

logbook-json/src/test/java/org/zalando/logbook/json/JsonPathBodyFiltersTest.java

Change the test when the body is unwrapped array

Change the test when the body is unwrapped array

---

README.md

The original example provided was not compatible with the current code.

Update README.md replaceBody filters example

---

pom.xml

Fixed coveralls usage in workflow

---

.github/workflows/build.yaml

Adjusted workflow job

---

logbook-parent/pom.xml
logbook-spring-boot-webflux-autoconfigure/pom.xml

Upgraded Spring

---

logbook-json/src/main/java/org/zalando/logbook/json/JsonPathBodyFilters.java
logbook-json/src/test/java/org/zalando/logbook/json/JsonPathBodyFiltersTest.java

Fix NPE in json replace filter

---

logbook-spring-webflux/src/main/java/org/zalando/logbook/spring/webflux/BufferingServerHttpRequest.java
logbook-spring-webflux/src/main/java/org/zalando/logbook/spring/webflux/BufferingServerHttpResponse.java
logbook-spring-webflux/src/main/java/org/zalando/logbook/spring/webflux/ClientRequest.java
logbook-spring-webflux/src/main/java/org/zalando/logbook/spring/webflux/ClientResponse.java
logbook-spring-webflux/src/main/java/org/zalando/logbook/spring/webflux/LogbookExchangeFilterFunction.java
logbook-spring-webflux/src/main/java/org/zalando/logbook/spring/webflux/LogbookWebFilter.java
logbook-spring-webflux/src/main/java/org/zalando/logbook/spring/webflux/ServerRequest.java
logbook-spring-webflux/src/main/java/org/zalando/logbook/spring/webflux/ServerResponse.java
logbook-spring-webflux/src/test/java/org/zalando/logbook/spring/webflux/BufferingServerHttpResponseUnitTest.java
logbook-spring-webflux/src/test/java/org/zalando/logbook/spring/webflux/LogbookExchangeFilterFunctionTest.java
logbook-spring-webflux/src/test/java/org/zalando/logbook/spring/webflux/LogbookWebFilterTest.java
logbook-spring-webflux/src/test/java/org/zalando/logbook/spring/webflux/TestApplication.java

logbook-webflux fixes

---

cve-suppressions.xml
logbook-httpclient/pom.xml
logbook-ktor-common/pom.xml
logbook-ktor-server/src/test/kotlin/org/zalando/logbook/server/LogbookServerTest.kt
logbook-parent/pom.xml
logbook-spring-boot-webflux-autoconfigure/pom.xml
logbook-spring-webflux/pom.xml
logbook-spring-webflux/src/test/java/org/zalando/logbook/spring/webflux/LogbookExchangeFilterFunctionTest.java
logbook-spring-webflux/src/test/java/org/zalando/logbook/spring/webflux/LogbookWebFilterTest.java

The PR should update the dependencies with vulnerabilites and make the build pass
The change will deblock the pipeline and update all the dependencies with vulnerabilites and make the build pass

Updating the dependencies and making the build pass

---

.github/dependabot.yml
cve-suppressions.xml
logbook-api/pom.xml
logbook-api/src/main/java/org/zalando/logbook/DefaultHttpHeaders.java
logbook-api/src/main/java/org/zalando/logbook/LogbookFactory.java
logbook-api/src/test/java/org/zalando/logbook/DefaultHttpHeadersTest.java
logbook-parent/pom.xml

closes https://github.com/zalando/logbook/issues/1497

Remove Paguro dependency from the project

---

.github/workflows/build.yaml

Remove GitHub Actions 'cache' action.  
This workflow is already using the 'cache' attribute for setup-java

Remove GitHub Actions Cache action

---

logbook-spring-webflux/src/main/java/org/zalando/logbook/spring/webflux/BufferingServerHttpRequest.java
logbook-spring-webflux/src/main/java/org/zalando/logbook/spring/webflux/LogbookWebFilter.java
logbook-spring-webflux/src/test/java/org/zalando/logbook/spring/webflux/LogbookWebFilterTest.java

log request/response for rejected requests

---

README.md

Documentation-only change. Adding a link to the high-level diagrams including module, library dependency and others (https://sourcespy.com/github/zalandologbook/). Built directly from source and updated on schedule.
Intended to simplify developer's introduction to the project.
In the spirit of transparency - I am the author of the diagrams. Hope contributors find it useful.

Add repository map link to README.md

---

.zappr.yaml

See https://github.com/zalando/logbook/issues/1596

Prevent Pull Request Self Approvals

---

cve-suppressions.xml

Suppressing CVE-2023-4586 as there are no mitigations for it as of now. The CVE is [not yet published](https://cve.report/CVE-2023-4586).

Suppress CVE-2023-4586

---

cve-suppressions.xml
logbook-parent/pom.xml

Dependency check errs on three vulnerabilities.

Fix dependency check issues

---

release.sh

Exclude issues with no-a-bug label from release
Relates to https://github.com/zalando/logbook/issues/1703

Exclude issues with no-a-bug label from release

---

logbook-parent/pom.xml
logbook-servlet/pom.xml
logbook-spring-boot-autoconfigure/pom.xml

Fix the scope of some dependencies.
Some dependencies must have the scope `test` or `provided`. Due to a recent change, Logbook transitively includes them on compile or runtime path (for Gradle project). This PR resets the dependency scopes back to what they were supposed to be, as in `3.6.0` version of Logbook.
Fixes #1711 
Here's the diff of the Gradle dependencies from `3.6` to `3.8.0-SNAPSHOT` (this PR):
```diff
71,78c71,78
< org.zalando:logbook-api:3.6.0=compileClasspath,productionRuntimeClasspath,runtimeClasspath,testCompileClasspath,testRuntimeClasspath
< org.zalando:logbook-common:3.6.0=compileClasspath,productionRuntimeClasspath,runtimeClasspath,testCompileClasspath,testRuntimeClasspath
< org.zalando:logbook-core:3.6.0=compileClasspath,productionRuntimeClasspath,runtimeClasspath,t …
```

Fix dependency scopes

---

.github/workflows/build.yaml

Follow-up of https://github.com/zalando/logbook/pull/1742
See https://github.com/zalando/logbook/actions/runs/7613871782 for example.

Check for Vulnerabilities via GHE Action

---

logbook-jaxrs/src/main/java/org/zalando/logbook/jaxrs/ByteStreams.java
logbook-jdkserver/src/main/java/org/zalando/logbook/jdkserver/ByteStreams.java
logbook-json/src/main/java/org/zalando/logbook/json/JacksonJsonFieldBodyFilter.java
logbook-openfeign/src/main/java/org/zalando/logbook/openfeign/ByteStreams.java
logbook-servlet/src/main/java/org/zalando/logbook/servlet/ByteStreams.java
logbook-servlet/src/test/java/org/zalando/logbook/servlet/ExampleController.java
logbook-spring/src/main/java/org/zalando/logbook/spring/ByteStreams.java

This merge request introduces improvements to the stream copying functionality. The existing static method has been refactored to use a dynamic buffer size and take advantage of try-with-resources for automatic stream closure and avoid using of `while(true)`. These changes enhance the clarity and maintainability of the code.
This merge request addresses the need to improve the efficiency and clarity of stream copying operations within the codebase.

Improve InputStream and OutputStream copying

---

logbook-api/src/main/java/org/zalando/logbook/RequestURI.java
logbook-api/src/test/java/org/zalando/logbook/RequestURITest.java
logbook-httpclient/src/test/java/org/zalando/logbook/httpclient/AbstractHttpTest.java
logbook-httpclient/src/test/java/org/zalando/logbook/httpclient/LogbookHttpInterceptorsPutTest.java

Adding a slash to the request path when reconstructing the request URI, if it's not present. 
https://github.com/zalando/logbook/issues/1793

Add slash to path if it's not present

---

logbook-ktor-client/src/main/kotlin/org/zalando/logbook/client/LogbookClient.kt
logbook-ktor-client/src/test/kotlin/org/zalando/logbook/client/LogbookClientTest.kt
logbook-ktor-common/src/main/kotlin/org/zalando/logbook/common/ContentUtils.kt

Wrapping Ktor client response handling in the coroutine context of HttpClient scope. 
Addresses #1822

wrap ktor client response handling into HttpClient context

---

.zappr.yaml

Add mandatory properties to .zappr
`COMPR/pr-specification` check fails on pull requests as stricter .zappr validation was enforced. This PR adds mandatory fields

Add mandatory properties to .zappr

---

logbook-core/src/main/java/org/zalando/logbook/core/FilteredHttpRequest.java
logbook-core/src/test/java/org/zalando/logbook/core/FilteredHttpRequestTest.java

When a `withoutBody` strategy is used then possible HttpAttributes won't be written to the sink. The problem is the difference in the HttpRequest object used to  send to the `writeBoth` method. I added the httpAttributes to the `FilteredHttpRequest` and adapted the `withRequest` method which will return a new `FilteredHttpRequest`  containing the original `HttpAttributes`.  Fixes #2024
see #2024

Add HttpAttributes To FilteredHttpRequest

---

logbook-jaxrs/src/main/java/org/zalando/logbook/jaxrs/LogbookServerFilter.java

Moved `response.expose()` to conditional logic to ensure it is only called when `hasEntity()` is true. This improves the clarity and correctness of the response handling process.
This fixes the issue as per my original fix in https://github.com/zalando/logbook/pull/1909, which was later changed during the review process.
* **Fix:** The fix is to call expose methods conditionally, only when the request/response entity exists.
* **Test:** I wasn't able to write an automated test to cover this, but the existing tests plus cover for all branches already.
* Use the project https://github.com/msdousti/quarkus-logbook
* Compile with the version of Logbook in this PR (`3.12.0-SNAPSHOT`)
* Run the project
* Send a GET and a HEAD request, and observe the console
This succeeds even without the …

Refactor response processing in LogbookServerFilter

---

CHANGELOG.md
logbook-api/pom.xml
logbook-bom/pom.xml
logbook-common/pom.xml
logbook-core/pom.xml
logbook-httpclient/pom.xml
logbook-httpclient5/pom.xml
logbook-jaxrs/pom.xml
logbook-jdkserver/pom.xml
logbook-jmh/pom.xml
logbook-json/pom.xml
logbook-ktor-client/pom.xml
logbook-ktor-common/pom.xml
logbook-ktor-server/pom.xml
logbook-ktor/pom.xml
logbook-logstash/pom.xml
logbook-netty/pom.xml
logbook-okhttp/pom.xml
logbook-okhttp2/pom.xml
logbook-openfeign/pom.xml
logbook-parent/pom.xml
logbook-servlet/pom.xml
logbook-spring-boot-autoconfigure/pom.xml
logbook-spring-boot-starter/pom.xml
logbook-spring-boot-webflux-autoconfigure/pom.xml
logbook-spring-webflux/pom.xml
logbook-spring/pom.xml
logbook-test/pom.xml
pom.xml

This change is representing 3.12.0 release

Release 3.12.0

---

CHANGELOG.md
logbook-api/pom.xml
logbook-bom/pom.xml
logbook-common/pom.xml
logbook-core/pom.xml
logbook-httpclient/pom.xml
logbook-httpclient5/pom.xml
logbook-jaxrs/pom.xml
logbook-jdkserver/pom.xml
logbook-jmh/pom.xml
logbook-json/pom.xml
logbook-ktor-client/pom.xml
logbook-ktor-common/pom.xml
logbook-ktor-server/pom.xml
logbook-ktor/pom.xml
logbook-logstash/pom.xml
logbook-netty/pom.xml
logbook-okhttp/pom.xml
logbook-okhttp2/pom.xml
logbook-openfeign/pom.xml
logbook-parent/pom.xml
logbook-servlet/pom.xml
logbook-spring-boot-autoconfigure/pom.xml
logbook-spring-boot-starter/pom.xml
logbook-spring-boot-webflux-autoconfigure/pom.xml
logbook-spring-webflux/pom.xml
logbook-spring/pom.xml
logbook-test/pom.xml
pom.xml

This change is representing 3.12.2 release

Release 3.12.2
